//! Auto-generated plugin registry — DO NOT EDIT
//! Generated by build.sh from plugins/*/main.conf
//! Regenerate by running: ./build.sh plugins (or any full build)
//!
//! Plugins compiled in: 2
//! To add a plugin:   create plugins/<n>/main.conf + <entry>.rs, rebuild kernel
//! To remove:         delete plugins/<n>/, rebuild kernel
//! To enable/disable: pluginctl enable/disable <n>  (no rebuild needed)

mod perf_monitor {
    include!("../../../plugins/perf_monitor/plug/main.rs");
}
mod syscall_logger {
    include!("../../../plugins/syscall_logger/plug/main.rs");
}

/// Register all compiled-in plugins with the kernel plugin manager.
/// Called once from kernel_main before plugins::init().
pub fn register_all() {

    crate::plugins::register(&perf_monitor::PLUGIN_ENTRY);
    crate::plugins::register(&syscall_logger::PLUGIN_ENTRY);

    // Sync HOOKS_ACTIVE counter with the number of initially-enabled plugins
    let enabled_count = crate::plugins::list()
        .iter()
        .filter(|(_name, enabled, _ver, _desc)| *enabled)
        .count() as u32;
    crate::plugins::hooks::HOOKS_ACTIVE.store(
        enabled_count,
        core::sync::atomic::Ordering::Relaxed,
    );
}
